config/routes.rb
Rails.application.routes.draw do
  get 'contact' => 'contacts#new'
  get 'contacts/create'
  get 'contacts/index'
  get 'about' => 'about#index'
  namespace :admin do
    get 'login' => 'sessions#new', :as =>'login'
    get 'sessions/create'
    get 'logout' => 'sessions#new', :as =>'logout'
  end
  namespace :admin do
    get 'users/new'
    get 'users/create'
    get 'users/edit'
    get 'users/update'
    get 'users/destroy'
    get 'users' => 'users#index'
    get 'users/show'
    post 'users' => 'users#create'
  end
  namespace :admin do
    get 'comments/destroy'
  end
  get 'comments/new'
  namespace :admin do
    get 'categories/new'
    get 'categories/create'
    get 'categories/edit'
    get 'categories/update'
    get 'categories/destroy'
    get 'categories/index'
    get 'categories/show'
  end
  get 'categories/show'
  namespace :admin do
    get 'posts/new'
    get 'posts/create'
    get 'posts/edit'
    get 'posts/update'
    get 'posts/destroy'
    get 'posts/index'
    get 'posts/show'
  end
  get 'posts/index'
  get 'posts/show'
  root 'posts#index'
  resources :posts, :categories
  resources "contacts", only: [:new, :create]

  namespace :admin do
    resources :posts, :categories, :comments, :sessions
  end
  resources :posts do
    resources :comments
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
    has_many :posts
    validates :name, presence: true
    def self.search(query)
        where("name like ?", "%#{query}%")
    end

end

app/models/comment.rb
class Comment < ApplicationRecord
    belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
    belongs_to :category
    belongs_to :user
    has_many :comments

    validates :title, presence: true
    validates :category_id, presence: true
    validates :body, presence: true

    has_attached_file :image, :default_url => ":style/Ruby_on_Rails-logo.png"
    validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
    def self.search(query)
        where("title like ? OR body like ?", "%#{query}%", "%#{query}%")
    end

end

app/models/user.rb
class User < ApplicationRecord
    attr_accessor :password
    before_save :encrypt_password

    has_many :posts

    validates :name, presence: true
    validates :email, presence: true
    # validates :password, presence: true
    validates :password, confirmation: true

    def self.authenticate(email, password)
        user = find_by_email(email)
        if user && user_password_hash == BCrypt::Engine.hash_secret(password, user_password_salt)
            user
        else
            nil
        end
    end
    def encrypt_password
        if password.present?
            self.password_salt = BCrypt::Engine.generate_salt
            self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)           
        end
    end
    def self.search(query)
        where("name like ? OR email like ?", "%#{query}%", "%#{query}%")
    end
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    protect_from_forgery with: :null_session
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def show
    @category = Category.find(params[:id])
    @categories = Category.all
    @posts = @category.posts
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.create(comment_params)
    flash[:notice] = 'Comment Added'
    redirect_to @post
  end
  def comment_params
    params.require(:comment).permit(:name, :email, :body, :post_id)
  end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def new
  end

  def create
  end

  def index
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    if params[:search]
      @posts = Post.search(params[:search]).all.order('created_at DESC').paginate(:per_page => 2, :page => params[:page])
    else
      @posts = Post.all.order('created_at DESC').paginate(:per_page => 2, :page => params[:page])
    end
    @categories = Category.all
  end

  def show
    @post = Post.find(params[:id])
    @categories = Category.all
    @comments = Comment.all
    @comment = Comment.new
  end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/admin/comments_helper.rb
module Admin::CommentsHelper
end

app/helpers/admin/posts_helper.rb
module Admin::PostsHelper
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/admin/application.html.erb
<!DOCTYPE html>
<html>
  <head>
  <%= csrf_meta_tags %>

       <title><%=  @title ? @title : "Welcome" %> | rbLOG</title>
  <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <%# <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %> 
  
    <%= stylesheet_link_tag 'admin/application', media: 'all', 'data-turbolinks-track': 'reload'   %>
  <%= javascript_include_tag 'admin/application', 'data-turbolinks-track' => true %>
  </head>

  <body>
<script type="text/javascript" src = "../../assets/froala_editor.pkgd.min.js"></script>

    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <a class="navbar-brand" href="posts.html">rBlog/Manager</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
      
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            <li class=<%= params[:controller] === 'admin/posts' ? 'active' : '' %>>
              <%= link_to 'Posts', admin_posts_path %>
            </li>
          </ul>
          <ul class="navbar-nav mr-auto">
            <li class=<%= params[:controller] === 'admin/categories' ? 'active' : '' %>>
              <%= link_to 'Categories', admin_categories_path %>
            </li>
             </ul>
          <ul class="navbar-nav mr-auto">
            <li class=<%= params[:controller] === 'admin/users' ? 'active' : '' %>>
              <%= link_to 'Users', admin_users_path %>
            </li>
           </ul>
       <%= render 'partials/search' %>
        </div>
      </nav>
      <section>
        <div class="container">
          <div class="row">
            <div class="col-md-12">
                <div class="well">
                  <% if current_user %>
                    Logged In As <%= current_user.email %>
                    <%= link_to 'Log Out', admin_logout_path %>
                  <% else %>
                    <%= link_to 'Log In', admin_login_path %>
                  <% end %>
                    <br/>
                    <% if flash[:notice] %>
                      <div class='alert alert-success'><%= flash[:notice] %></div>
                    <% end %>
                    <% if flash[:alert] %>
                      <div class='alert alert-danger'><%= flash[:alert] %></div>
                    <% end %> 
                    <br/>
                    <%= yield %>
                </div>
            </div>
          </div>
        </div>
      </section>
      <footer>
        <p>CopyRight &copy: 2020, rBlog | <%= link_to "FrontEnd", root_path %></a> </p>
      </footer>
   
  </body>
</html>

app/views/layouts/admin/login.html.erb
<!DOCTYPE html>
<html>
  <head>
  <%= csrf_meta_tags %>

       <title><%=  @title ? @title : "Login" %> | rbLOG</title>
  <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <%# <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %> 
  
    <%= stylesheet_link_tag 'admin/login', media: 'all', 'data-turbolinks-track': 'reload'   %>
  </head>

  <body>
    <div class="container">
        <%= yield %>
    </div>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%=  @title ? @title : "Welcome" %> | rbLOG</title>
  <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>

  </head>

  <body>

    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="/">rBlog</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
      
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            <li class=<%= params[:controller] == 'post' ? 'nav-item active' : 'nav-item' %>>
              <%= link_to 'Home', root_path%>
            </li>
          </ul>
          <ul class="navbar-nav mr-auto">

            <li class=<%= params[:controller] == 'contact' ? 'nav-item active' : 'nav-item' %>>
              <%= link_to 'Contact', contact_path%>
            </li>
               </ul>
          <ul class="navbar-nav mr-auto">
            <li class=<%= params[:controller] == 'about' ? 'nav-item active' : 'nav-item' %>>
              <%= link_to 'About', about_path%>
            </li>
          </ul>
                                

            <%# <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Dropdown
              </a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                <a class="dropdown-item" href="#">Action</a>
                <a class="dropdown-item" href="#">Another action</a>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item" href="#">Something else here</a>
              </div>
            </li> %>
            <%= render 'partials/search' %>
        </div>
      </nav>
      <section>
        <div class="container">
          <div class="row">
            <div class="col-md-8">
            <% if flash[:notice] %>
              <div class='alert alert-success'><%= flash[:notice] %></div>
            <% end %>
            <% if flash[:alert] %>
              <div class='alert alert-danger'><%= flash[:alert] %></div>
            <% end %>
                    <%= yield %>
            </div>
            <div class="col-md-4">
                <%= render 'partials/sidebar' %>
            </div>
          </div>
        </div>
      </section>
        <%= render 'partials/footer' %>
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script type="text/javascript" src = "../../assets/froala_editor.pkgd.min.js"></script>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>

app/views/partials/_comments.html.erb
<div class="comments">
<h2 class="page-header"><%= @post.comments.length %> Comments</h2>
<% @post.comments.each do |comment| %>
  <div class="comment">
    <div class="row">
        <div class="col-md-2">
          <%= image_tag("user.jpg") %>
        </div>
        <div class="col-md-10">
        <div class="well">
            <h4><%= comment.name %><span><%= comment.created_at.to_time.strftime('%B %e at %l:%M %p') %></span></h4>
            <%= comment.body %>
        </div>
        </div>
    </div>
  </div>
<% end %>
<br/>
<br/>

<div class="well add-comment">
<h2 class="page-header">Add Comment</h2>
<%= form_for([@post, @post.comments.build]) do |f| %>
    <div class="form-group">
        <%= f.label :name %>
        <%= f.text_field :name, class: 'form-control' %>
    </div>
    <div class="form-group">
        <%= f.label :email %>
        <%= f.text_field :email, class: 'form-control' %>
    </div>
    <div class="form-group">
        <%= f.label :body %>
        <%= f.text_field :body, class: 'form-control' %>
    </div>
    <div class="form-group">
        <%= f.submit 'Submit', class: 'btn btn-primary' %>
        <%= link_to 'Back', root_path, class: 'btn btn-danger' %>
    </div>
<% end %>
</div>
</div>

app/views/partials/_footer.html.erb
      <footer>
        <p>CopyRight &copy: 2020, rBlog | <a href="login.html">Admin Login</a> </p>
      </footer>

app/views/partials/_search.html.erb
<% if params[:controller] == "admin/posts" %>
<%= form_tag(admin_posts_path, :method => "get", id: "search-form", class: "form-inline my-2 my-lg-0") do %>
    <div class="form-group">
        <%= text_field_tag :search, params[:search], placeholder: "Search Posts", class: "form-control mr-sm-2" %>
    </div>
    <%= submit_tag "Search", :name => nil, class:"btn btn-outline-success my-2 my-sm-0" %>
<% end %>
<% elsif params[:controller] == "admin/categories" %>
<%= form_tag(admin_categories_path, :method => "get", id: "search-form", class: "form-inline my-2 my-lg-0") do %>
    <div class="form-group">
        <%= text_field_tag :search, params[:search], placeholder: "Search Categories", class: "form-control mr-sm-2" %>
    </div>
    <%= submit_tag "Search", :name => nil, class:"btn btn-outline-success my-2 my-sm-0" %>
<% end %>
<% elsif params[:controller] == "admin/users" %>
<%= form_tag(admin_users_path, :method => "get", id: "search-form", class: "form-inline my-2 my-lg-0") do %>
    <div class="form-group">
        <%= text_field_tag :search, params[:search], placeholder: "Search Users", class: "form-control mr-sm-2" %>
    </div>
    <%= submit_tag "Search", :name => nil, class:"btn btn-outline-success my-2 my-sm-0" %>
<% end %>
<% elsif params[:controller] == "posts" %>
<%= form_tag(posts_path, :method => "get", id: "search-form", class: "form-inline my-2 my-lg-0") do %>
    <div class="form-group">
        <%= text_field_tag :search, params[:search], placeholder: "Search Posts", class: "form-control mr-sm-2" %>
    </div>
    <%= submit_tag "Search", :name => nil, class:"btn btn-outline-success my-2 my-sm-0" %>
<% end %>
<% end %>

app/views/partials/_sidebar.html.erb
<% if params[:controller] == 'posts' || params[:controller] == 'categories'   %>
 <ul class="list-group"> 
<% @categories.each do |category| %> 
   <li class="list-group-item"><%= link_to category.name, category_path(category.id) %></li> 
<% end %>
</ul>  
<% end %>