config/routes.rb
Rails.application.routes.draw do
  get 'contact' => 'contacts#new'
  get 'contacts/create'
  get 'contacts/index'
  get 'about' => 'about#index'
  namespace :admin do
    get 'login' => 'sessions#new', :as =>'login'
    get 'sessions/create'
    get 'logout' => 'sessions#new', :as =>'logout'
  end
  namespace :admin do
    get 'users/new'
    get 'users/create'
    get 'users/edit'
    get 'users/update'
    get 'users/destroy'
    get 'users' => 'users#index'
    get 'users/show'
    post 'users' => 'users#create'
  end
  namespace :admin do
    get 'comments/destroy'
  end
  get 'comments/new'
  namespace :admin do
    get 'categories/new'
    get 'categories/create'
    get 'categories/edit'
    get 'categories/update'
    get 'categories/destroy'
    get 'categories/index'
    get 'categories/show'
  end
  get 'categories/show'
  namespace :admin do
    get 'posts/new'
    get 'posts/create'
    get 'posts/edit'
    get 'posts/update'
    get 'posts/destroy'
    get 'posts/index'
    get 'posts/show'
  end
  get 'posts/index'
  get 'posts/show'
  root 'posts#index'
  resources :posts, :categories
  resources "contacts", only: [:new, :create]

  namespace :admin do
    resources :posts, :categories, :comments, :sessions
  end
  resources :posts do
    resources :comments
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
    has_many :posts
    validates :name, presence: true
    def self.search(query)
        where("name like ?", "%#{query}%")
    end

end

app/models/comment.rb
class Comment < ApplicationRecord
    belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
    belongs_to :category
    belongs_to :user
    has_many :comments

    validates :title, presence: true
    validates :category_id, presence: true
    validates :body, presence: true

    has_attached_file :image, :default_url => ":style/Ruby_on_Rails-logo.png"
    validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
    def self.search(query)
        where("title like ? OR body like ?", "%#{query}%", "%#{query}%")
    end

end

app/models/user.rb
class User < ApplicationRecord
    attr_accessor :password
    before_save :encrypt_password

    has_many :posts

    validates :name, presence: true
    validates :email, presence: true
    # validates :password, presence: true
    validates :password, confirmation: true

    def self.authenticate(email, password)
        user = find_by_email(email)
        if user && user_password_hash == BCrypt::Engine.hash_secret(password, user_password_salt)
            user
        else
            nil
        end
    end
    def encrypt_password
        if password.present?
            self.password_salt = BCrypt::Engine.generate_salt
            self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)           
        end
    end
    def self.search(query)
        where("name like ? OR email like ?", "%#{query}%", "%#{query}%")
    end
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index
  end
end

app/controllers/admin/comments_controller.rb
class Admin::CommentsController < Admin::ApplicationController
  def destroy
  end
end

app/controllers/admin/posts_controller.rb
class Admin::PostsController < Admin::ApplicationController
  before_action :verify_logged_in

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    if params[:post][:image].blank?
      @post.image = nil
    end
    if @post.save
      flash[:notice] = 'Post Created'
      redirect_to admin_posts_path
    else
      render 'new'
    end
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    if params[:post][:image].blank?
      @post.image = nil
    end
    if @post.update(post_params)
      flash[:notice] = 'Post Updated'
      redirect_to admin_posts_path
    else
      render 'edit'
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    flash[:notice] = 'Post Deleted'
    redirect_to admin_posts_path
  end

  def index
    if params[:search]
      @posts = Post.search(params[:search]).all.order('created_at DESC').paginate(:per_page => 2, :page => params[:page])
    else
      @posts = Post.all.order('created_at DESC').paginate(:per_page => 2, :page => params[:page])
    end
  end

  def show
  end
  private def post_params 
    params.require(:post).permit(:title, :category_id, :user_id, :tags, :image, :body)  
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:notice] = 'User Created'
      redirect_to admin_users_path
    else
      render 'new'
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice] = 'User Updated'
      redirect_to admin_users_path
    else
      render 'edit'
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    flash[:notice] = 'User Deleted'
    redirect_to admin_users_path
  end

  def index
    if params[:search]
      @users = User.search(params[:search]).all.order('created_at DESC').paginate(:per_page => 2, :page => params[:page])
    else
      @users = User.all.order('created_at DESC').paginate(:per_page => 2, :page => params[:page])
    end
  end

  def show
  end
  private def user_params 
    params.require(:user).permit(:name, :email, :passward)  
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    protect_from_forgery with: :null_session
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def show
    @category = Category.find(params[:id])
    @categories = Category.all
    @posts = @category.posts
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.create(comment_params)
    flash[:notice] = 'Comment Added'
    redirect_to @post
  end
  def comment_params
    params.require(:comment).permit(:name, :email, :body, :post_id)
  end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def new
  end

  def create
  end

  def index
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    if params[:search]
      @posts = Post.search(params[:search]).all.order('created_at DESC').paginate(:per_page => 2, :page => params[:page])
    else
      @posts = Post.all.order('created_at DESC').paginate(:per_page => 2, :page => params[:page])
    end
    @categories = Category.all
  end

  def show
    @post = Post.find(params[:id])
    @categories = Category.all
    @comments = Comment.all
    @comment = Comment.new
  end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/admin/categories_helper.rb
module Admin::CategoriesHelper
end

app/helpers/admin/comments_helper.rb
module Admin::CommentsHelper
end

app/helpers/admin/posts_helper.rb
module Admin::PostsHelper
end

app/helpers/admin/sessions_helper.rb
module Admin::SessionsHelper
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/admin/comments/destroy.html.erb
<h1>Admin::Comments#destroy</h1>
<p>Find me in app/views/admin/comments/destroy.html.erb</p>

app/views/admin/posts/edit.html.erb
<h1>Edit Post</h1>
<%= form_for [:admin, @post] do |f| %>

    <% if @post.errors.any? %>
      <% @post.errors.full_messages.each do |msg| %>
        <div class="alert alert-danger"><%= msg %></div>
      <% end %>
    <% end %>

    <div class="form-group">
        <%= f.label :title %>
        <%= f.text_field :title , class: 'form-control' %>
    </div>
    <div class="form-group">
        <%= f.label :category %>
        <%= f.select :category_id, Category.all.collect {|x| [x.name, x.id]}, {:include_blank => 'Select One'} , class: 'form-control' %>
    </div>
    <div class="form-group">
        <%= f.label :author %>
        <%= f.select :user_id , User.all.collect{|x| [x.name, x.id]}, {:include_blank => 'Select One'}, class: 'form-control' %>
    </div>
    <div class="form-group">
        <%= f.label :image %>
        <%= f.file_field :image  %>
    </div>
    <% if @post.image.exists? %>
      <%= image_tag @post.image.url, width:'10%' %>
    <% end %>
    <div class="form-group">
        <%= f.label :tags %>
        <%= f.text_area :tags , class: 'form-control' %>
    </div>
    <br/>
        <div class="form-group">
        <%= f.label :body %>
        <%= f.text_area :body , class: 'form-control' %>
    </div>
    <br/>
    <br/>
    <%= f.submit 'Submit', class:'btn btn-primary' %>
    <%= link_to 'Cancel', admin_posts_path, class:'btn btn-danger' %>
<% end %>

app/views/admin/posts/index.html.erb
<div class="well">
<h2 class="page-header">Manage Posts <%= link_to "Add New", new_admin_post_path , class:"btn btn-success"%></h2>      
<% if @posts.exists? %>

    <table class="table table-striped">
        <tr>
            <th>Post Title </th>
            <th>Post Categories </th>
            <th>Create Date</th>
            <th>Actions</th>
        </tr>
        <% @posts.each do |post| %>
            <tr>
                <td><%= post.title %></td>
                <td><%= post.category_id %></td>
                <td><%= post.created_at.to_time.strftime('%B %e at %l:%M %p') %></td>
                <td><%= link_to "Edit", edit_admin_post_path(post.id), class:"btn btn-primary" %>  
                    <%= link_to "Delete", admin_post_path(post), method: :delete, data:{confirm: "Are you sure!"}, class:"btn btn-danger" %> 
                </td>
            </tr>
        <% end %>
    </table>
    <%= will_paginate @posts %>
<% else %>
    <h3>There Are No Posts</h3>
<% end %>

</div>

app/views/admin/posts/new.html.erb
<script>
  new FroalaEditor('textarea#froala-editor')
</script>

<h1>New Post</h1>

<%= form_for [:admin, @post] do |f| %>

    <% if @post.errors.any? %>
      <% @post.errors.full_messages.each do |msg| %>
        <div class="alert alert-danger"><%= msg %></div>
      <% end %>
    <% end %>

    <div class="form-group">
        <%= f.label :title %>
        <%= f.text_field :title , class: 'form-control' %>
    </div>
    <div class="form-group">
        <%= f.label :category %>
        <%= f.select :category_id, Category.all.collect {|x| [x.name, x.id]}, {:include_blank => 'Select One'} , class: 'form-control' %>
    </div>
    <div class="form-group">
        <%= f.label :author %>
        <%= f.select :user_id , User.all.collect{|x| [x.name, x.id]}, {:include_blank => 'Select One'}, class: 'form-control' %>
    </div>
    <div class="form-group">
        <%= f.label :image %>
        <%= f.file_field :image  %>
    </div>
    <div class="form-group">
        <%= f.label :tags %>
        <%= f.text_area :tags , class: 'form-control' %>
    </div>
    <br/>
        <div class="form-group">
        <%= f.label :body %>
        <%= f.text_area :body , class: 'form-control', id:"froala-editor" %>
    </div>
    <br/>
    <br/>
    <%= f.submit 'Submit', class:'btn btn-primary' %>
    <%= link_to 'Cancel', admin_posts_path, class:'btn btn-danger' %>
<% end %>

app/views/posts/index.html.erb
<div class="row">
  <% @posts.each do |post| %>
    <div class="col-md-6">
      <div class="post">
        <%= image_tag post.image.url, width: '50%' %>
        <div class="post-content">
          <h3><%= post.title %></h3>
          <small>Post by:<%= post.user.name %> On <%= post.created_at.to_time.strftime('%B %e at %l:%M %p') %></small>
          <%= raw post.body.truncate(200) %>
          <%= link_to 'Read More', post_path(post), class: "btn btn-primary btn-block" %>
        </div>
      </div>
    </div>   
  <% end %>
</div>

app/views/posts/show.html.erb
<div class="weel post-single">
<h2 class="page-header"><%= @post.title %></h2>
<div class="post-content">
    <small>Post by:<%= @post.user.name %> On <%= @post.created_at.to_time.strftime('%B %e at %l:%M %p') %></small>
    <p><%= raw @post.body %></p>
</div>
    <%= image_tag @post.image.url, width: '50%' %>
  </div>

<%= render 'partials/comments' %>