config/routes.rb
Rails.application.routes.draw do
  get 'contact' => 'contacts#new'
  get 'contacts/create'
  get 'contacts/index'
  get 'about' => 'about#index'
  namespace :admin do
    get 'login' => 'sessions#new', :as =>'login'
    get 'sessions/create'
    get 'logout' => 'sessions#new', :as =>'logout'
  end
  namespace :admin do
    get 'users/new'
    get 'users/create'
    get 'users/edit'
    get 'users/update'
    get 'users/destroy'
    get 'users' => 'users#index'
    get 'users/show'
    post 'users' => 'users#create'
  end
  namespace :admin do
    get 'comments/destroy'
  end
  get 'comments/new'
  namespace :admin do
    get 'categories/new'
    get 'categories/create'
    get 'categories/edit'
    get 'categories/update'
    get 'categories/destroy'
    get 'categories/index'
    get 'categories/show'
  end
  get 'categories/show'
  namespace :admin do
    get 'posts/new'
    get 'posts/create'
    get 'posts/edit'
    get 'posts/update'
    get 'posts/destroy'
    get 'posts/index'
    get 'posts/show'
  end
  get 'posts/index'
  get 'posts/show'
  root 'posts#index'
  resources :posts, :categories
  resources "contacts", only: [:new, :create]

  namespace :admin do
    resources :posts, :categories, :comments, :sessions
  end
  resources :posts do
    resources :comments
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/category.rb
class Category < ApplicationRecord
    has_many :posts
    validates :name, presence: true
    def self.search(query)
        where("name like ?", "%#{query}%")
    end

end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < Admin::ApplicationController
  before_action :verify_logged_in
  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      flash[:notice] = 'Category Created'
      redirect_to admin_categories_path
    else
      render 'new'
    end
  end

  def edit
    @category = Category.find(params[:id])
  end

  def update
    @category = Category.find(params[:id])
    if @category.update(category_params)
      flash[:notice] = 'Ctaegory Updated'
      redirect_to admin_categories_path
    else
      render 'edit'
    end
  end

  def destroy
    @category = Category.find(params[:id])
    @category.destroy
    flash[:notice] = 'Ctaegory Deleted'
    redirect_to admin_categories_path
  end

  def index
    if params[:search]
      @categories = Category.search(params[:search]).all.order('created_at DESC').paginate(:per_page => 2, :page => params[:page])
    else
      @categories = Category.all.order('created_at DESC').paginate(:per_page => 2, :page => params[:page])
    end
  end

  def show
  end
  private def category_params
    params.require(:category).permit(:name)
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def show
    @category = Category.find(params[:id])
    @categories = Category.all
    @posts = @category.posts
  end
end

app/helpers/admin/categories_helper.rb
module Admin::CategoriesHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/admin/categories/edit.html.erb
<h1>Edit Category</h1>
<%= form_for [:admin, @category] do |f| %>

    <% if @category.errors.any? %>
      <% @categort.errors.full_messages.each do |msg| %>
        <div class="alert alert-danger"><%= msg %></div>
      <% end %>
    <% end %>

    <div class="form-group">
        <%= f.label :name %>
        <%= f.text_field :name , class: 'form-control' %>
    </div>
    <br/>
    <%= f.submit 'Submit', class:'btn btn-primary' %>
    <%= link_to 'Cancel', admin_categories_path, class:'btn btn-danger' %>
<% end %>

app/views/admin/categories/index.html.erb
<div class="well">
    <h2 class="page-header">Manage Categories <%= link_to "Add New", new_admin_category_path, class:"btn btn-success"%></h2>      
    <table class="table table-striped">
        <tr>
            <th>Category Title </th>
            <th>Create Date</th>
            <th>Actions</th>
        </tr>
        <% @categories.each do |category| %>
            <tr>
                <td><%= category.name %></td>
                <td><%= category.created_at.to_time.strftime('%B %e at %l:%M %p') %></td>
                <td><%= link_to "Edit", edit_admin_category_path(category.id), class:"btn btn-primary" %>  
                    <%= link_to "Delete", admin_category_path(category), method: :delete, data: { confirm: "Are you sure!" }, class:"btn btn-danger" %> 
                </td>
            </tr>
        <% end %>
    </table>
    <%= will_paginate @categories %>
</div>

app/views/admin/categories/new.html.erb
<h1>New Category</h1>
<%= form_for [:admin, @category] do |f| %>

    <% if @category.errors.any? %>
      <% @categort.errors.full_messages.each do |msg| %>
        <div class="alert alert-danger"><%= msg %></div>
      <% end %>
    <% end %>

    <div class="form-group">
        <%= f.label :name %>
        <%= f.text_field :name , class: 'form-control' %>
    </div>
    <br/>
    <%= f.submit 'Submit', class:'btn btn-primary' %>
    <%= link_to 'Cancel', admin_categories_path, class:'btn btn-danger' %>
<% end %>